export const missionScaffolds = {
  introduction: {
    key: 'introduction',
    missionId: 'introduction',
    title: 'Introduction to DSA',
    subtitle: 'Foundation lesson',
    description: 'Build your core understanding of data structures, ADT concepts, and algorithms.',
    accent: '#0ea5e9',
    gradient: 'from-[#0ea5e9] via-[#2563eb] to-[#7c3aed]',
    stageLabel: 'Introduction Mission',
    rewardLabel: 'DSA Starter Pack',
    hint: 'Focus on key terms and how each concept connects to real program behavior.',
    introBlurb: 'This introduction covers the core building blocks needed before deeper DSA topics.',
    reviewBlurb: 'Review each subtopic and make sure you can explain the purpose of data structures, ADT, and algorithms.',
    preTest: {
      title: 'Pre-test',
      prompt: 'What best describes a data structure?',
      choices: ['A way to store and organize data', 'A type of screen layout', 'A network cable format', 'A compiler setting'],
      correctIndex: 0,
      questions: [
        {
          prompt: 'What best describes a data structure?',
          choices: ['A way to store and organize data', 'A type of screen layout', 'A network cable format', 'A compiler setting'],
          correctIndex: 0,
          explanation: 'Data structures define how data is arranged so programs can use it efficiently.',
        },
        {
          prompt: 'Which type is considered linear?',
          choices: ['Array', 'Tree', 'Graph', 'Heap'],
          correctIndex: 0,
          explanation: 'Arrays are linear because elements are arranged in sequence.',
        },
        {
          prompt: 'What does ADT stand for?',
          choices: ['Abstract Data Type', 'Advanced Data Table', 'Applied Data Tool', 'Array Definition Type'],
          correctIndex: 0,
          explanation: 'ADT means Abstract Data Type.',
        },
        {
          prompt: 'Which is a common ADT operation?',
          choices: ['Insert', 'Compile', 'Render', 'Install'],
          correctIndex: 0,
          explanation: 'Insert is one of the common ADT operations.',
        },
        {
          prompt: 'What is an algorithm?',
          choices: ['A step-by-step set of instructions', 'A data container', 'A computer brand', 'A file extension'],
          correctIndex: 0,
          explanation: 'An algorithm is a clear sequence of steps used to solve a problem.',
        },
      ],
    },
    postTest: {
      title: 'Post-test',
      prompt: 'After this introduction lesson, what should you understand clearly?',
      choices: ['Data structures, ADT concepts, operations, and algorithms', 'Only one quiz question', 'Only the mission score', 'Only the navigation buttons'],
      correctIndex: 0,
    },
    introPoints: [
      'Data structures store and organize data.',
      'ADT defines behavior, not implementation details.',
      'Algorithms are step-by-step procedures for solving problems.',
    ],
    introSubtopics: [
      {
        title: 'Subtopic 1: What is a Data Structure?',
        terms: ['Data structure', 'Store', 'Organize', 'Data'],
        explanation:
          'A data structure is a special format used to store and organize data. It helps a program manage data properly so that the data can be added, accessed, updated, or removed when needed.',
        simpleExplanation: 'Data structures are like containers. Each container has a different way of keeping data.',
      },
      {
        title: 'Subtopic 2: Linear and Non-linear Data Structures',
        terms: ['Linear', 'Non-linear'],
        explanation: 'This subtopic explains how some structures arrange data in sequence (linear) while others branch into multiple connections (non-linear).',
        simpleExplanation: 'Linear is like a line. Non-linear is like branches.',
      },
      {
        title: 'Subtopic 3: What is an ADT?',
        terms: ['ADT', 'Abstract Data Type'],
        explanation: 'This subtopic introduces ADT as a concept that describes what operations are allowed, without forcing one specific implementation.',
        simpleExplanation: 'ADT tells what a structure should do, not exactly how to code it.',
      },
      {
        title: 'Subtopic 4: ADT Examples',
        terms: ['List ADT', 'Stack ADT', 'Queue ADT'],
        explanation: 'This subtopic presents common ADT examples used in programming and problem solving.',
        simpleExplanation: 'Examples of ADT include List, Stack, and Queue.',
      },
      {
        title: 'Subtopic 5: ADT Operations',
        terms: ['Insert', 'Delete', 'Search', 'Traverse'],
        explanation: 'This subtopic focuses on common operations that ADTs support when handling data.',
        simpleExplanation: 'Operations are actions like add, remove, find, and visit data.',
      },
      {
        title: 'Subtopic 6: What is an Algorithm?',
        terms: ['Algorithm', 'Steps', 'Problem solving'],
        explanation: 'This subtopic defines an algorithm as a finite sequence of steps used to solve a task or computational problem.',
        simpleExplanation: 'An algorithm is a clear set of steps to solve something.',
      },
    ],
    visualNodes: ['Data', 'Structure', 'Operation', 'Algorithm'],
    codeStarter: ['// Introduction mission starter', 'const topic = "Introduction to DSA";', 'console.log(topic);'].join('\n'),
    codeHint: 'Code editor content can be updated per topic.',
    problem: {
      title: 'Problem: Identify the concept',
      prompt: 'Given a short scenario, identify whether it describes a data structure, an ADT, an operation, or an algorithm.',
      starter: ['// Write your answer mapping here', 'const answer = {};', '', 'console.log(answer);'].join('\n'),
      hint: 'Look at whether the statement describes storage, abstract behavior, actions, or step-by-step logic.',
      requiredFragments: ['const', 'answer'],
      solutionNote: 'A correct answer classifies each scenario into the right concept category.',
    },
  },
  recursion: {
    key: 'recursion',
    missionId: 'recursion',
    title: '02 Recursion',
    subtitle: 'Concept foundation',
    description: 'Understand recursion clearly before moving to code implementation.',
    accent: '#4d8ecb',
    gradient: 'from-[#2b67ad] via-[#4d8ecb] to-[#8b5cf6]',
    stageLabel: 'Recursion Mission',
    rewardLabel: 'Stack Mastery Pack',
    hint: 'Focus on how recursive calls repeat, how they stop, and how each call moves toward a base case.',
    introBlurb: 'This lesson explains recursion conceptually using clear terms and guided examples before writing code.',
    reviewBlurb: 'Post-test review will point back to introduction and visualization steps.',
    preTest: {
      title: 'Pre-test',
      prompt: 'Which idea best matches recursion?',
      choices: ['A function that repeats by calling itself', 'A loop with a fixed counter', 'A list of values in order', 'A class that stores data'],
      correctIndex: 0,
      questions: [
        {
          prompt: 'Which idea best matches recursion?',
          choices: ['A function that repeats by calling itself', 'A loop with a fixed counter', 'A list of values in order', 'A class that stores data'],
          correctIndex: 0,
          explanation: 'Recursion is when a function calls itself to solve smaller instances of the same problem.',
        },
        {
          prompt: 'What is the base case used for?',
          choices: ['To stop the recursive calls', 'To start a loop', 'To store input values', 'To print the answer only'],
          correctIndex: 0,
          explanation: 'The base case defines when the recursion should stop to avoid infinite calls.',
        },
        {
          prompt: 'What happens when the base case is never reached?',
          choices: ['The function keeps calling itself', 'The function turns into a loop', 'The program always finishes', 'The result is always zero'],
          correctIndex: 0,
          explanation: 'If there is no base case reached, recursion continues until the call stack overflows or the program crashes.',
        },
        {
          prompt: 'Why is recursion useful?',
          choices: ['It can simplify repeating patterns', 'It removes the need for any input', 'It only works on text files', 'It replaces all variables'],
          correctIndex: 0,
          explanation: 'Recursion can make code easier to write and read for problems that naturally divide into similar subproblems.',
        },
        {
          prompt: 'What must every recursive function have?',
          choices: ['A base case', 'A timer', 'A database', 'A screen refresh'],
          correctIndex: 0,
          explanation: 'A base case is necessary to terminate recursion; without it calls never end.',
        },
      ],
    },
    postTest: {
      title: 'Post-test',
      prompt: 'After this lesson, what should a review of recursion focus on?',
      choices: ['Introduction and visualization', 'Only the first question', 'Only the progress bar', 'Only the reward card'],
      correctIndex: 0,
    },
    introPoints: [
      'Recursion is when a function calls itself to solve a problem.',
      'A base case is required so recursion can stop.',
      'Each recursive step should move the problem toward the base case.',
    ],
    introSubtopics: [
      {
        title: 'Subtopic 1: What is Recursion?',
        terms: ['Recursion', 'Recursive function', 'Function calls itself'],
        explanation:
          'Recursion is a process where a function calls itself once or multiple times to solve a problem. Any function that calls itself is called a recursive function.',
        simpleExplanation: 'Recursion happens when a function repeats by calling itself.',
        guideText:
          'A recursive function solves a problem by doing the same process again on a smaller or simpler version of the problem.',
      },
      {
        title: 'Subtopic 2: Types of Recursive Calls',
        terms: ['Direct recursion', 'Indirect recursion', 'Infinite recursion'],
        explanation:
          'Direct recursion happens when a method directly calls itself. Indirect recursion happens when a method calls another method, and that method eventually calls the original method again. Infinite recursion happens when a recursive function fails to stop.',
        simpleExplanation:
          'Direct recursion calls itself directly. Indirect recursion goes through another function first. Infinite recursion keeps repeating without stopping.',
        guideText:
          'A recursive process must have a way to stop. Without a stopping condition, the function may continue calling itself forever.',
      },
      {
        title: 'Subtopic 3: Parts of a Recursive Algorithm',
        terms: ['Base case', 'Change of state', 'Recursive call'],
        explanation:
          'A recursive algorithm must have three important parts. First, it must have a base case, which is the condition that allows the recursion to stop. Second, it must change its state and move toward the base case. Third, it must call itself recursively.',
        simpleExplanation: 'Every recursion needs a stopping point, a change, and a self-call.',
        guideText:
          'The base case prevents infinite recursion. The change of state moves the problem closer to that base case. The recursive call repeats the process.',
      },
      {
        title: 'Subtopic 4: Recursion vs Iteration',
        terms: ['Recursion', 'Iteration', 'Looping', 'Base case', 'Condition', 'Stack overflow'],
        explanation:
          'Iteration is a process of repeating a set of instructions, also known as looping. Recursion stops when a base case is reached, while iteration stops when a condition becomes false. Each recursive call requires extra memory space, while iteration does not require extra memory space for repeated calls. Infinite recursion may cause stack overflow.',
        simpleExplanation: 'Recursion repeats by calling itself. Iteration repeats using a loop.',
        guideText:
          'Both recursion and iteration repeat actions, but they repeat in different ways. Recursion uses repeated function calls, while iteration uses loops.',
      },
      {
        title: 'Subtopic 5: Types of Recursion',
        terms: ['Linear recursion', 'Tail recursion', 'Binary recursion', 'Mutual recursion'],
        explanation:
          'Linear recursion happens when a function calls itself once each time it is invoked. Tail recursion happens when the recursive call is the last operation of the function. Binary recursion happens when the function calls itself twice. Mutual recursion happens when functions work in a pair or group by calling one another.',
        simpleExplanation: 'The type of recursion depends on how the function calls itself.',
        guideText:
          'Some recursive functions call themselves once, some call themselves twice, and some work together with other functions.',
      },
    ],
    introMockData: [],
    visualNodes: ['Base Case', 'Recursive Call', 'Return Path'],
    recursionVisualization: {
      functionLabel: 'countdown(n)',
      inputValue: 3,
      frameDurationMs: 1300,
      steps: [
        {
          phase: 'call',
          label: 'countdown(3)',
          caption: 'Recursive call begins with countdown(3).',
        },
        {
          phase: 'call',
          label: 'countdown(2)',
          caption: 'State changes from 3 to 2.',
        },
        {
          phase: 'call',
          label: 'countdown(1)',
          caption: 'State changes from 2 to 1.',
        },
        {
          phase: 'base',
          label: 'countdown(0)',
          caption: 'Base case reached. Stop recursive calls.',
        },
        {
          phase: 'return',
          label: 'countdown(0) returns',
          caption: 'Return starts from the base case.',
        },
        {
          phase: 'return',
          label: 'countdown(1) finishes',
          caption: 'The waiting call for countdown(1) finishes.',
        },
        {
          phase: 'return',
          label: 'countdown(2) finishes',
          caption: 'The waiting call for countdown(2) finishes.',
        },
        {
          phase: 'return',
          label: 'countdown(3) finishes',
          caption: 'Return reaches the first call and recursion completes.',
        },
      ],
    },
    codeStarter: ['function recurse(value) {', '  return value;', '}'].join('\n'),
    codeHint: 'Code editor content can be updated per topic.',
    problem: {
      title: 'Problem: Complete the recursion',
      prompt: 'Finish the function so it counts down from n to 1 using recursion.',
      starter: ['function countDown(n) {', '  // add base case and recursive step', '}', '', 'countDown(3);'].join('\n'),
      hint: 'You need a base case and a recursive call that reduces the number.',
      requiredFragments: ['if', 'countDown(n - 1)', 'return'],
      solutionNote: 'A correct answer should stop at the base case and call itself with a smaller value.',
    },
  },
  iteration: {
    key: 'iteration',
    missionId: 'iteration',
    title: 'Iteration',
    subtitle: 'Lesson Module',
    description: 'Loop-based lesson content.',
    accent: '#22c55e',
    gradient: 'from-[#0ea5e9] via-[#22c55e] to-[#f59e0b]',
    stageLabel: 'Iteration Mission',
    rewardLabel: 'Loop Builder Pack',
    hint: 'This topic is currently locked.',
    introBlurb: 'This topic is currently locked.',
    reviewBlurb: 'Post-test review will point back to introduction and visualization steps.',
    preTest: {
      title: 'Pre-test',
      prompt: 'Which pattern fits iteration best?',
      choices: ['Repeating steps with a loop', 'Calling the same function again', 'Storing nodes in links', 'Writing a one-time note'],
      correctIndex: 0,
      questions: [
        {
          prompt: 'Which pattern fits iteration best?',
          choices: ['Repeating steps with a loop', 'Calling the same function again', 'Storing nodes in links', 'Writing a one-time note'],
          correctIndex: 0,
          explanation: 'Iteration uses loops to repeat a block of code until a condition is met.',
        },
        {
          prompt: 'Which keyword often starts a loop?',
          choices: ['for', 'return', 'class', 'breakpoint'],
          correctIndex: 0,
          explanation: 'Keywords like `for` and `while` commonly start loops that perform iteration.',
        },
        {
          prompt: 'What is the purpose of a loop condition?',
          choices: ['To decide when the loop stops', 'To store the final result only', 'To create a new function', 'To make the screen bigger'],
          correctIndex: 0,
          explanation: 'The loop condition determines whether the loop continues or finishes.',
        },
        {
          prompt: 'Which is a loop counter?',
          choices: ['A variable that tracks iterations', 'A function that ends recursion', 'A file name', 'An image asset'],
          correctIndex: 0,
          explanation: 'A loop counter is a variable that keeps track of how many times the loop has run.',
        },
        {
          prompt: 'Why use iteration?',
          choices: ['To repeat work efficiently', 'To remove all variables', 'To avoid any output', 'To turn code into text'],
          correctIndex: 0,
          explanation: 'Iteration repeats tasks with minimal code and is efficient for many repeated operations.',
        },
      ],
    },
    postTest: {
      title: 'Post-test',
      prompt: 'What should the review cover after the iteration lesson?',
      choices: ['Introduction and visualization', 'Only the answers you missed', 'Only the first stage', 'Only the final score'],
      correctIndex: 0,
    },
    introPoints: ['Loop overview', 'Iteration objectives', 'Topic walkthrough'],
    visualNodes: ['Start', 'Condition', 'Update', 'Repeat'],
    codeStarter: ['for (let i = 0; i < 3; i += 1) {', '  console.log(i);', '}'].join('\n'),
    codeHint: 'Code editor content can be updated per topic.',
    problem: {
      title: 'Problem: Sum with a loop',
      prompt: 'Write a loop that adds numbers from 1 to 5 and stores the total in sum.',
      starter: ['let sum = 0;', '', '// write your loop here', '', 'console.log(sum);'].join('\n'),
      hint: 'You need a loop, a counter, and an addition step.',
      requiredFragments: ['for', 'sum +=', '5'],
      solutionNote: 'A correct answer loops from 1 to 5 and increases sum each time.',
    },
  },
  'linked-list': {
    key: 'linked-list',
    missionId: 'linked-list',
    title: 'Linked List',
    subtitle: 'Lesson Module',
    description: 'Linked list lesson content.',
    accent: '#ec4899',
    gradient: 'from-[#8b5cf6] via-[#ec4899] to-[#f97316]',
    stageLabel: 'Linked List Mission',
    rewardLabel: 'Pointer Flow Pack',
    hint: 'This topic is currently locked.',
    introBlurb: 'This topic is currently locked.',
    reviewBlurb: 'Post-test review will point back to introduction and visualization steps.',
    preTest: {
      title: 'Pre-test',
      prompt: 'What best describes a linked list?',
      choices: ['A chain of nodes connected by pointers', 'A single value stored in a table', 'A loop that counts upward', 'A text file with labels'],
      correctIndex: 0,
      questions: [
        {
          prompt: 'What best describes a linked list?',
          choices: ['A chain of nodes connected by pointers', 'A single value stored in a table', 'A loop that counts upward', 'A text file with labels'],
          correctIndex: 0,
          explanation: 'A linked list is a sequence of nodes where each node points to the next node in the list.',
        },
        {
          prompt: 'What does each node usually store?',
          choices: ['A value and a reference to the next node', 'Only the entire list', 'A loop counter', 'A keyboard shortcut'],
          correctIndex: 0,
          explanation: 'Nodes typically hold a value and a pointer/reference to the next node in the list.',
        },
        {
          prompt: 'What is the head of a linked list?',
          choices: ['The first node', 'The last node', 'The number of nodes', 'The memory address of the screen'],
          correctIndex: 0,
          explanation: 'The head is the first node of the list and is the entry point for traversals.',
        },
        {
          prompt: 'What does a pointer do?',
          choices: ['Points to another node in memory', 'Runs the program faster by itself', 'Prints the output', 'Creates a loop automatically'],
          correctIndex: 0,
          explanation: 'Pointers reference the location of another node, allowing traversal from one node to the next.',
        },
        {
          prompt: 'What happens at the end of the list?',
          choices: ['The next pointer is null', 'The list becomes a tree', 'The value is doubled', 'The node becomes a loop'],
          correctIndex: 0,
          explanation: 'The end of a linked list is usually represented by a null/none pointer indicating no further nodes.',
        },
      ],
    },
    postTest: {
      title: 'Post-test',
      prompt: 'What should the review cover after the linked list lesson?',
      choices: ['Introduction and visualization', 'Only the first node', 'Only the reward card', 'Only the sidebar'],
      correctIndex: 0,
    },
    introPoints: ['Node structure', 'Pointer explanation', 'Traversal example'],
    visualNodes: ['Head', 'Node', 'Node', 'Null'],
    codeStarter: ['class Node {', '  constructor(value) {', '    this.value = value;', '  }', '}'].join('\n'),
    codeHint: 'Code editor content can be updated per topic.',
    problem: {
      title: 'Problem: Count the nodes',
      prompt: 'Complete the function so it counts how many nodes are in the linked list.',
      starter: ['function countNodes(head) {', '  let count = 0;', '  // traverse the list', '  return count;', '}'].join('\n'),
      hint: 'Move through each node until you reach null.',
      requiredFragments: ['while', 'current', 'count++'],
      solutionNote: 'A correct answer walks through the list and increments count for every node.',
    },
  },
};

export function getMissionScaffold(key) {
  return missionScaffolds[key] || missionScaffolds.recursion;
}
