export const missionScaffolds = {
  recursion: {
    key: 'recursion',
    missionId: 'recursion',
    title: 'Recursion',
    subtitle: 'Reusable mission scaffold',
    description: 'Pre-test, intro, visualization, and post-test all live in one shared lesson shell.',
    accent: '#4d8ecb',
    gradient: 'from-[#2b67ad] via-[#4d8ecb] to-[#8b5cf6]',
    stageLabel: 'Recursion Mission',
    rewardLabel: 'Stack Mastery Pack',
    hint: 'Trace how recursive calls break Tower of Hanoi into smaller moves until a base case is reached.',
    introBlurb: 'Tower of Hanoi is a classic recursion problem: move n-1 disks out of the way, move the largest disk, then move n-1 disks again. The same pattern repeats on smaller stacks.',
    reviewBlurb: 'Post-test review will point back to introduction and visualization steps.',
    preTest: {
      title: 'Pre-test',
      prompt: 'Which idea best matches recursion?',
      choices: ['A function that repeats by calling itself', 'A loop with a fixed counter', 'A list of values in order', 'A class that stores data'],
      correctIndex: 0,
      questions: [
        {
          prompt: 'Which idea best matches recursion?',
          choices: ['A function that repeats by calling itself', 'A loop with a fixed counter', 'A list of values in order', 'A class that stores data'],
          correctIndex: 0,
          explanation: 'Recursion is when a function calls itself to solve smaller instances of the same problem.',
        },
        {
          prompt: 'What is the base case used for?',
          choices: ['To stop the recursive calls', 'To start a loop', 'To store input values', 'To print the answer only'],
          correctIndex: 0,
          explanation: 'The base case defines when the recursion should stop to avoid infinite calls.',
        },
        {
          prompt: 'What happens when the base case is never reached?',
          choices: ['The function keeps calling itself', 'The function turns into a loop', 'The program always finishes', 'The result is always zero'],
          correctIndex: 0,
          explanation: 'If there is no base case reached, recursion continues until the call stack overflows or the program crashes.',
        },
        {
          prompt: 'Why is recursion useful?',
          choices: ['It can simplify repeating patterns', 'It removes the need for any input', 'It only works on text files', 'It replaces all variables'],
          correctIndex: 0,
          explanation: 'Recursion can make code easier to write and read for problems that naturally divide into similar subproblems.',
        },
        {
          prompt: 'What must every recursive function have?',
          choices: ['A base case', 'A timer', 'A database', 'A screen refresh'],
          correctIndex: 0,
          explanation: 'A base case is necessary to terminate recursion; without it calls never end.',
        },
      ],
    },
    postTest: {
      title: 'Post-test',
      prompt: 'After the lesson scaffold, what should a review of recursion focus on?',
      choices: ['Introduction and visualization', 'Only the first question', 'Only the progress bar', 'Only the reward card'],
      correctIndex: 0,
    },
    introPoints: ['Every recursive plan needs a base case (1 disk)', 'A big move is solved by two smaller subproblems', 'Rules stay consistent: move one disk at a time, never place bigger on smaller'],
    introMockData: [
      { label: 'Puzzle', value: 'Tower of Hanoi' },
      { label: 'Disks', value: '3' },
      { label: 'Minimum Moves', value: '7' },
      { label: 'Formula', value: '2^n - 1' },
    ],
    visualNodes: ['Base Case', 'Recursive Call', 'Return Path'],
    recursionVisualization: {
      functionLabel: 'solveHanoi(n, source, helper, target)',
      inputValue: 3,
      frameDurationMs: 1400,
      steps: [
        {
          phase: 'call',
          label: 'Start: solveHanoi(3, A, B, C)',
          caption: 'Initial state. We need to move all disks from Tower A to Tower C.',
          pegs: { A: [3, 2, 1], B: [], C: [] },
        },
        {
          phase: 'move',
          label: 'Move 1: A -> C (disk 1)',
          caption: 'Base move from the first recursive branch.',
          pegs: { A: [3, 2], B: [], C: [1] },
        },
        {
          phase: 'move',
          label: 'Move 2: A -> B (disk 2)',
          caption: 'Move the next disk so the largest disk can eventually move.',
          pegs: { A: [3], B: [2], C: [1] },
        },
        {
          phase: 'move',
          label: 'Move 3: C -> B (disk 1)',
          caption: 'Complete the first subproblem: stack smaller disks on Tower B.',
          pegs: { A: [3], B: [2, 1], C: [] },
        },
        {
          phase: 'base',
          label: 'Move 4: A -> C (disk 3)',
          caption: 'Core/base action for n=3: move the largest disk to Tower C.',
          pegs: { A: [], B: [2, 1], C: [3] },
        },
        {
          phase: 'move',
          label: 'Move 5: B -> A (disk 1)',
          caption: 'Start second recursive branch: move smaller disks onto the target tower.',
          pegs: { A: [1], B: [2], C: [3] },
        },
        {
          phase: 'move',
          label: 'Move 6: B -> C (disk 2)',
          caption: 'Continue unwinding recursive calls toward completion.',
          pegs: { A: [1], B: [], C: [3, 2] },
        },
        {
          phase: 'return',
          label: 'Move 7: A -> C (disk 1)',
          caption: 'Final move. All disks are now on Tower C.',
          pegs: { A: [], B: [], C: [3, 2, 1] },
        },
      ],
    },
    codeStarter: ['function recurse(value) {', '  // scaffold only', '  return value;', '}'].join('\n'),
    codeHint: 'Editable code scaffold. Replace this placeholder later with a topic-specific editor.',
    problem: {
      title: 'Problem: Complete the recursion',
      prompt: 'Finish the function so it counts down from n to 1 using recursion.',
      starter: ['function countDown(n) {', '  // add base case and recursive step', '}', '', 'countDown(3);'].join('\n'),
      hint: 'You need a base case and a recursive call that reduces the number.',
      requiredFragments: ['if', 'countDown(n - 1)', 'return'],
      solutionNote: 'A correct answer should stop at the base case and call itself with a smaller value.',
    },
  },
  iteration: {
    key: 'iteration',
    missionId: 'iteration',
    title: 'Iteration',
    subtitle: 'Reusable mission scaffold',
    description: 'The same lesson shell hosts loop-based content with guided visual checks.',
    accent: '#22c55e',
    gradient: 'from-[#0ea5e9] via-[#22c55e] to-[#f59e0b]',
    stageLabel: 'Iteration Mission',
    rewardLabel: 'Loop Builder Pack',
    hint: 'This mission is a placeholder shell for iteration content.',
    introBlurb: 'Intro content will be inserted here later.',
    reviewBlurb: 'Post-test review will point back to introduction and visualization steps.',
    preTest: {
      title: 'Pre-test',
      prompt: 'Which pattern fits iteration best?',
      choices: ['Repeating steps with a loop', 'Calling the same function again', 'Storing nodes in links', 'Writing a one-time note'],
      correctIndex: 0,
      questions: [
        {
          prompt: 'Which pattern fits iteration best?',
          choices: ['Repeating steps with a loop', 'Calling the same function again', 'Storing nodes in links', 'Writing a one-time note'],
          correctIndex: 0,
          explanation: 'Iteration uses loops to repeat a block of code until a condition is met.',
        },
        {
          prompt: 'Which keyword often starts a loop?',
          choices: ['for', 'return', 'class', 'breakpoint'],
          correctIndex: 0,
          explanation: 'Keywords like `for` and `while` commonly start loops that perform iteration.',
        },
        {
          prompt: 'What is the purpose of a loop condition?',
          choices: ['To decide when the loop stops', 'To store the final result only', 'To create a new function', 'To make the screen bigger'],
          correctIndex: 0,
          explanation: 'The loop condition determines whether the loop continues or finishes.',
        },
        {
          prompt: 'Which is a loop counter?',
          choices: ['A variable that tracks iterations', 'A function that ends recursion', 'A file name', 'An image asset'],
          correctIndex: 0,
          explanation: 'A loop counter is a variable that keeps track of how many times the loop has run.',
        },
        {
          prompt: 'Why use iteration?',
          choices: ['To repeat work efficiently', 'To remove all variables', 'To avoid any output', 'To turn code into text'],
          correctIndex: 0,
          explanation: 'Iteration repeats tasks with minimal code and is efficient for many repeated operations.',
        },
      ],
    },
    postTest: {
      title: 'Post-test',
      prompt: 'What should the review cover after the iteration scaffold?',
      choices: ['Introduction and visualization', 'Only the answers you missed', 'Only the first stage', 'Only the final score'],
      correctIndex: 0,
    },
    introPoints: ['Loop overview placeholder', 'Iteration objective placeholder', 'Walkthrough placeholder'],
    visualNodes: ['Start', 'Condition', 'Update', 'Repeat'],
    codeStarter: ['for (let i = 0; i < 3; i += 1) {', '  // scaffold only', '  console.log(i);', '}'].join('\n'),
    codeHint: 'Editable code scaffold. Replace this placeholder later with a loop-based editor.',
    problem: {
      title: 'Problem: Sum with a loop',
      prompt: 'Write a loop that adds numbers from 1 to 5 and stores the total in sum.',
      starter: ['let sum = 0;', '', '// write your loop here', '', 'console.log(sum);'].join('\n'),
      hint: 'You need a loop, a counter, and an addition step.',
      requiredFragments: ['for', 'sum +=', '5'],
      solutionNote: 'A correct answer loops from 1 to 5 and increases sum each time.',
    },
  },
  'linked-list': {
    key: 'linked-list',
    missionId: 'linked-list',
    title: 'Linked List',
    subtitle: 'Reusable mission scaffold',
    description: 'The shared shell can present node traversal and pointer flow through guided visuals.',
    accent: '#ec4899',
    gradient: 'from-[#8b5cf6] via-[#ec4899] to-[#f97316]',
    stageLabel: 'Linked List Mission',
    rewardLabel: 'Pointer Flow Pack',
    hint: 'This mission is a placeholder shell for linked list content.',
    introBlurb: 'Intro content will be inserted here later.',
    reviewBlurb: 'Post-test review will point back to introduction and visualization steps.',
    preTest: {
      title: 'Pre-test',
      prompt: 'What best describes a linked list?',
      choices: ['A chain of nodes connected by pointers', 'A single value stored in a table', 'A loop that counts upward', 'A text file with labels'],
      correctIndex: 0,
      questions: [
        {
          prompt: 'What best describes a linked list?',
          choices: ['A chain of nodes connected by pointers', 'A single value stored in a table', 'A loop that counts upward', 'A text file with labels'],
          correctIndex: 0,
          explanation: 'A linked list is a sequence of nodes where each node points to the next node in the list.',
        },
        {
          prompt: 'What does each node usually store?',
          choices: ['A value and a reference to the next node', 'Only the entire list', 'A loop counter', 'A keyboard shortcut'],
          correctIndex: 0,
          explanation: 'Nodes typically hold a value and a pointer/reference to the next node in the list.',
        },
        {
          prompt: 'What is the head of a linked list?',
          choices: ['The first node', 'The last node', 'The number of nodes', 'The memory address of the screen'],
          correctIndex: 0,
          explanation: 'The head is the first node of the list and is the entry point for traversals.',
        },
        {
          prompt: 'What does a pointer do?',
          choices: ['Points to another node in memory', 'Runs the program faster by itself', 'Prints the output', 'Creates a loop automatically'],
          correctIndex: 0,
          explanation: 'Pointers reference the location of another node, allowing traversal from one node to the next.',
        },
        {
          prompt: 'What happens at the end of the list?',
          choices: ['The next pointer is null', 'The list becomes a tree', 'The value is doubled', 'The node becomes a loop'],
          correctIndex: 0,
          explanation: 'The end of a linked list is usually represented by a null/none pointer indicating no further nodes.',
        },
      ],
    },
    postTest: {
      title: 'Post-test',
      prompt: 'What should the review cover after the linked list scaffold?',
      choices: ['Introduction and visualization', 'Only the first node', 'Only the reward card', 'Only the sidebar'],
      correctIndex: 0,
    },
    introPoints: ['Node structure placeholder', 'Pointer explanation placeholder', 'Traversal example placeholder'],
    visualNodes: ['Head', 'Node', 'Node', 'Null'],
    codeStarter: ['class Node {', '  constructor(value) {', '    this.value = value;', '  }', '}'].join('\n'),
    codeHint: 'Editable code scaffold. Replace this placeholder later with a linked-list editor.',
    problem: {
      title: 'Problem: Count the nodes',
      prompt: 'Complete the function so it counts how many nodes are in the linked list.',
      starter: ['function countNodes(head) {', '  let count = 0;', '  // traverse the list', '  return count;', '}'].join('\n'),
      hint: 'Move through each node until you reach null.',
      requiredFragments: ['while', 'current', 'count++'],
      solutionNote: 'A correct answer walks through the list and increments count for every node.',
    },
  },
};

export function getMissionScaffold(key) {
  return missionScaffolds[key] || missionScaffolds.recursion;
}
